slogan: â€œä½ å¦‚æœè¿‡äºè¿½æ±‚å®Œç¾ï¼Œå°†æ°¸è¿œæ— æ³•æ„Ÿåˆ°æ»¡è¶³ï¼ˆå®Œç¾ä¸»ä¹‰é™·é˜±ï¼‰ã€‚å‡†å¤‡å·®ä¸å¤šäº†ï¼Œå°±å»åšå§ï¼â€
email: 1315474340@qq.com
logo: "/images/logo.svg"

mathjax: false # åŠ è½½ LateX æ•°å­¦å…¬å¼åº“

favicon: # é…ç½®ç½‘é¡µå›¾æ ‡
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/logo.svg

subpage: # å¼€å¯â€œå­é¡µâ€åŠŸèƒ½ï¼Œè¯¦è§ README
  enable: true
  pages:
    - name: developer # æ–‡ç« çš„åˆ†ç±»ï¼ˆcategoryï¼‰åï¼Œå¦‚ developer
      path: developer # è‹¥ä¸è®¾ç½®åˆ™é»˜è®¤ä½¿ç”¨ name
      title: æŠ€æœ¯ # èœå•åï¼Œå¦‚ å¼€å‘è€…
      icon: /images/icon/icon-code.svg # å›¾æ ‡çš„è·¯å¾„
      description: å‰ç«¯ã€åç«¯ã€æ¨¡å—æŠ€æœ¯çš„æ€æƒ³äº†è§£ã€å®è·µ # æè¿°
    - name: project # æ–‡ç« çš„åˆ†ç±»ï¼ˆcategoryï¼‰åï¼Œå¦‚ developer
      path: project # è‹¥ä¸è®¾ç½®åˆ™é»˜è®¤ä½¿ç”¨ name
      title: é¡¹ç›® # èœå•åï¼Œå¦‚ å¼€å‘è€…
      icon: /images/icon/icon-pi.svg # å›¾æ ‡çš„è·¯å¾„
      description: æ•ˆèƒ½å·¥å…·ã€æœ‰è¶£é¡¹ç›®ï¼Œè¯„ä¼°å¯è¡Œæ€§ï¼Œæœ‰ç”¨å°±å¹²èµ·æ¥ï¼ # æè¿°
    - name: essay # æ–‡ç« çš„åˆ†ç±»ï¼ˆcategoryï¼‰åï¼Œå¦‚ developer
      path: essay # è‹¥ä¸è®¾ç½®åˆ™é»˜è®¤ä½¿ç”¨ name
      title: éšè®° # èœå•åï¼Œå¦‚ å¼€å‘è€…
      icon: /images/icon/icon-blog.svg # å›¾æ ‡çš„è·¯å¾„
      description: è®¤çŸ¥ã€æ€ç»´ã€è¯»ä¹¦ã€å†™ä½œ # æè¿°




index: # é…ç½®é¦–é¡µä¸ªæ€§åŒ–å†…å®¹
  motto: "å°½äººäº‹ï¼Œå¬å¤©å‘½ï¼"
  poem:
    - é•¿é£ç ´æµªä¼šæœ‰æ—¶
    - ç›´æŒ‚äº‘å¸†æµæ²§æµ·ï¼
  photo: /images/about.jpg
  about:
    title: æˆ‘
    text:
      - å®›å¦‚æ˜Ÿè¾°ä¸­ä¸€é¢—å¾®èŠ’ï¼ŒæœŸå¾…ç»½æ”¾è‡ªå·±çš„å…‰èŠ’
      - 
      - ä¸–ç•Œä¸Šæœ€é‡è¦çš„äº‹å°±æ˜¯è®¤è¯†è‡ªæˆ‘

foot:
  title:
    - "å®é™æ·¡æ³Š"
    - "é™è‹¥ç©ºæ˜"

links: # æœ‹å‹
  # - name: "Theme Tranquility"
  #   url: https://github.com/hooozen/hexo-theme-tranquility

social:
  - name: "yyi0708"
    icon: "/images/logo-github.svg"
    url: https://github.com/yyi0708

reward: # èµèµ
  enable: true
  face: /assets/profile.jpg # å¤´åƒå›¾ç‰‡
  paycode: /assets/pay-code.jpg # æ”¯ä»˜ç å›¾ç‰‡
  text: â€œç»™ä½œè€…æœªæ¥ä¹°ä¸ªç¯æ³¡ğŸ’¡â€
  btnText: ä½œè€…æœ‰ç‚¹ä¸œè¥¿

# see https://github.com/gitalk/gitalk
gitalk: # gitalk è¯„è®º
  enable: true
  owner: # MUST HAVE, Your Github Username
  admin:
  repo: # MUST HAVE, The name of the repo you use to store Gitment comments
  clientID: # MUST HAVE, Github client id for the Gitment
  clientSecret: # EITHER this or proxy_gateway, Github access secret token for the Gitment

  distractionFreeMode: false # Facebook-like distraction free mode
  # When the official proxy is not available, you can change it to your own proxy address
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # This is official proxy adress
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN

# see https://github.com/tea3/hexo-related-popular-posts
related_post:
  enable: true
  config:
    maxCount: 5 # Maximum count of a list. default 5
    ulClass: # Class name of element. deafult 'popular-posts'
    PPMixingRate: 0.4 # Mixing ratio of popular posts and related posts. default 0.0(=Related posts only)
    isDate: # visible the date. false
    isImage: # visible the image. false
    isExcerpt: # visible the excerpt. false
    PPCategoryFilter: # Option to fix category on Popular Posts. undefined
    PPTagFilter: # Option to fix tag on Popular Posts. undefined

# Baidu Webmaster tools verification.
# See: https://ziyuan.baidu.com/site
baidu_site_verification:

# Baidu Analytics
# See: https://tongji.baidu.com
baidu_analytics: # <app_id>

# è‡ªå®šä¹‰å­—ä½“ï¼Œç”¨äºç¾åŒ–éƒ¨åˆ†æ±‰å­—çš„æ˜¾ç¤ºæ•ˆæœ.
# å¯ä»¥é€šè¿‡æ›¿æ¢ _font/ ç›®å½•ä¸‹çš„å­—ä½“æ–‡ä»¶æ›¿æ¢è‡ªå·±å–œæ¬¢çš„å­—ä½“
zh_font:
  enable: true
  fontName: sourceHanSerif
  type: ttf
  style:
    - normal
    - bold


# æ ‡ç­¾äº‘
tagcloud:
  fancy: false
  min_font: 14
  max_font: 30

# é…ç½®æ—¶é—´çº¿ å‚è€ƒ README.md
timeline:
  enable: true
  order: false # æ˜¯å¦æŒ‰æ—¶é—´æ­£åºå±•ç¤ºï¼Œfalse ä¸ºå€’åº
  items:
    - name: front-end
      color: "#ee936c"
      icon: /images/icon/icon-article.svg
      checked: true
    - name: back-end
      color: "#60a465"
      icon: /images/icon/icon-app.svg
      checked: true
    - name: project
      color: "#e0f2f0"
      icon: /images/icon/icon-app.svg
      checked: false
    - name: life
      color: "#568dc4"
      icon: /images/icon/icon-event.svg
      checked: true

mermaid:
  enable: true # å¯ç”¨ Mermaid å¢å¼º
  version: latest
  options:
    startOnload: true

cv:
  enable: true
  showInNav: true
  iconPrefix: fas
  keywords: ç®€å†,æç™½
  description: æç™½çš„ç®€å†
  title: æç™½çš„ç®€å†
  content:
    title: æç™½
    baseInfo:
      - å”æœ
      - è¯—äºº
      - å¤ªç™½
      - é’è²å±…å£«
    tel: å…«å…«å…«å…«å…«
    email: 1315474340@qq.com
    github: æš‚æ— 
    blog: Tranquility
    blogHref: https://theme.hozen.site/tranquility/
    edu:
      title: "æ•™è‚²èƒŒæ™¯"
      content:
        - 701 è‡³ 715ï¼Œä¿®ä¹ è¯—è¯å‰‘æœ¯
        - 718 è‡³ 724ï¼Œèœ€åœ°éšå±…
    chapters:
      - title: "ä»£è¡¨ä½œå“"
        icon: person-digging
        tips: è¯·ç‚¹å‡»é¡¹ç›®åç§°æŸ¥çœ‹é¡¹ç›®è¯¦æƒ…
        sections:
          - title: èœ€é“éš¾
            link: https://so.gushiwen.cn/shiwenv_d59ec5d6c91c.aspx
            description: ä¹åºœè¯—ã€æµªæ¼«ä¸»ä¹‰
            content:
              - å¤©å®å…ƒå¹´
              - è¿™é¦–è¯—æ˜¯è¢­ç”¨ä¹åºœæ—§é¢˜ï¼Œæ„åœ¨é€å‹äººå…¥èœ€ã€‚è¯—äººä»¥æµªæ¼«ä¸»ä¹‰çš„æ‰‹æ³•ï¼Œå±•å¼€ä¸°å¯Œçš„æƒ³è±¡ï¼Œè‰ºæœ¯åœ°å†ç°äº†èœ€é“å³¥åµ˜ï¼Œçªå…€ï¼Œå¼ºæ‚ã€å´å²–ç­‰å¥‡ä¸½æƒŠé™©å’Œä¸å¯å‡Œè¶Šçš„ç£…ç¤´æ°”åŠ¿ï¼Œå€Ÿä»¥æ­Œå’èœ€åœ°å±±å·çš„å£®ç§€ï¼Œæ˜¾ç¤ºå‡ºç¥–å›½å±±æ²³çš„é›„ä¼Ÿå£®ä¸½ã€‚
              - è‡³äºæœ¬è¯—æ˜¯å¦æœ‰æ›´æ·±çš„å¯“æ„ï¼Œå†ä»£æœ‰å„ç§ä¸åŒçœ‹æ³•ã€‚ç„¶è€Œå°±è¯—è®ºè¯—ï¼Œä¸ä¸€å®šå¼ºææœ‰å¯“æ„ã€‚ä½†ä»è¯—ä¸­ï¼Œâ€œæ‰€å®ˆæˆ–åŒªäº²ï¼ŒåŒ–ä¸ºç‹¼ä¸è±ºâ€çœ‹ï¼Œå´æ˜¯åœ¨å†™èœ€åœ°å±±å·å³»ç¾çš„åŒæ—¶ï¼Œå‘Šè¯«å½“å±€ï¼Œèœ€åœ°é™©è¦ï¼Œåº”å¥½å¥½ç”¨äººé˜²å®ˆã€‚
              - è¯—é‡‡ç”¨å¾‹ä½“ä¸æ•£æ–‡é—´æ‚ï¼Œæ–‡å¥å‚å·®ï¼Œç¬”æ„çºµæ¨ªï¼Œè±ªæ”¾æ´’è„±ã€‚å…¨è¯—æ„Ÿæƒ…å¼ºçƒˆï¼Œä¸€å”±ä¸‰å¹ï¼Œå›ç¯åå¤ï¼Œè¯»æ¥ä»¤äººå¿ƒæ½®æ¿€è¡ã€‚
          - title: å°†è¿›é…’
            link: https://so.gushiwen.cn/shiwenv_ee16df5673bc.aspx
            description: ä¹åºœä¸ƒè¨€æ­Œè¡Œ
            content:
              - å¼€å…ƒäºŒåäºŒå¹´
              - è¿™é¦–è¯—æ˜¯è¯—äººå½“æ—¶å’Œå‹äººå²‘å‹‹åœ¨åµ©å±±å¦ä¸€è€å‹å…ƒä¸¹ä¸˜çš„é¢é˜³å±±å±…ä½œå®¢ï¼Œä½œè€…æ­£å€¼ä»•é€”é‡æŒ«ä¹‹é™…ï¼Œæ‰€ä»¥å€Ÿé…’å…´è¯—ï¼Œæ¥äº†ä¸€æ¬¡é…£ç•…æ·‹æ¼“çš„æŠ’å‘ã€‚åœ¨è¿™é¦–è¯—é‡Œï¼Œæç™½â€œå€Ÿé¢˜å‘æŒ¥â€ï¼Œå€Ÿé…’æ¶ˆæ„ï¼Œæ„Ÿå¹äººç”Ÿæ˜“è€ï¼ŒæŠ’å‘äº†è‡ªå·±æ€€æ‰ä¸é‡çš„å¿ƒæƒ…ã€‚
              - è¿™é¦–è¯—ååˆ†å½¢è±¡çš„ä½“ç°äº†æç™½æ¡€éªœä¸é©¯çš„æ€§æ ¼ï¼šå¯¹è‡ªå·±å……æ»¡è‡ªä¿¡ã€å­¤é«˜è‡ªå‚²ã€çƒ­æƒ…è±ªæ”¾ï¼Œâ€œå¤©ç”Ÿæˆ‘æå¿…æœ‰ç”¨â€ã€â€œäººç”Ÿå¾—æ„é¡»å°½æ¬¢â€ã€‚å…¨è¯—æ°”åŠ¿è±ªè¿ˆï¼Œæ„Ÿæƒ…è±ªæ”¾ï¼Œè¨€è¯­æµç•…ï¼Œå…·æœ‰æå¼ºçš„æ„ŸæŸ“åŠ›ã€‚æç™½å’é…’çš„è¯—æ­Œéå¸¸èƒ½ä½“ç°ä»–çš„ä¸ªæ€§ï¼Œæ€æƒ³å†…å®¹æ·±æ²‰ï¼Œè‰ºæœ¯è¡¨ç°æˆç†Ÿã€‚ã€Šå°†è¿›é…’ã€‹å³ä¸ºå…¶ä»£è¡¨ä½œã€‚
      - title: å·¥ä½œç»éªŒ
        icon: laptop-code
        sections:
          - title: å¤§å”ç¿°æ—ä¾›å¥‰
            description: 743 - 744
            content:
              - èµå®«é”¦è¢ã€‚æš®æ˜¥ï¼Œå…´åº†æ± ç‰¡ä¸¹ç››å¼€ï¼Œç„å®—ä¸æ¨ç‰ç¯åŒèµï¼Œæç™½åˆå¥‰è¯ä½œã€Šæ¸…å¹³è°ƒã€‹ã€‚å¯¹å¾¡ç”¨æ–‡äººç”Ÿæ´»æ—¥æ¸åŒå€¦ï¼Œå§‹çºµé…’ä»¥è‡ªæ˜ç§½ã€‚
              - ä¸è´ºçŸ¥ç« ç­‰äººç»“â€œé…’ä¸­å…«ä»™â€ä¹‹æ¸¸ï¼Œç„å®—å‘¼ä¹‹ä¸æœã€‚å°å¥‰è¯é†‰ä¸­èµ·è‰è¯ä¹¦ï¼Œå¼•è¶³ä»¤é«˜åŠ›å£«è„±é´ï¼Œå®«ä¸­äººæ¨ä¹‹ï¼Œè°—è°¤äºç„å®—ï¼Œç„å®—ç–ä¹‹ï¼Œåç„å®—èµé‡‘æ”¾è¿˜ã€‚
      - title: è£èª‰å¥–é¡¹
        icon: trophy
        list: true
        content:
          - è¯—ä»™
          - é…’ä¸­å…«ä»™
      - title: ä¸ªäººå°ç»“
        icon: ranking-star
        content:
          - ä¸ºäººçˆ½æœ—å¤§æ–¹ï¼Œä¹äºäº¤å‹ï¼Œçˆ±å¥½é¥®é…’ä½œè¯—ï¼Œååˆ—â€œé…’ä¸­å…«ä»™â€  ã€‚æ›¾ç»å¾—åˆ°å”ç„å®—æéš†åŸºèµè¯†ï¼Œæ‹…ä»»ç¿°æ—ä¾›å¥‰ï¼Œ èµé‡‘æ”¾è¿˜ï¼Œæ¸¸å†å…¨å›½ï¼Œå…ˆåè¿å¨¶å®°ç›¸è®¸åœ‰å¸ˆã€å®—æ¥šå®¢çš„å­™å¥³ã€‚å”è‚ƒå®—å³ä½åï¼Œå·å…¥æ°¸ç‹ä¹‹ä¹±ï¼Œæµæ”¾å¤œéƒï¼Œè¾—è½¬åˆ°è¾¾å½“æ¶‚å¿ä»¤æé˜³å†°å®¶ã€‚ä¸Šå…ƒäºŒå¹´ï¼Œå»ä¸–ï¼Œæ—¶å¹´å…­åäºŒã€‚
          - è‘—æœ‰ã€Šæå¤ªç™½é›†ã€‹ï¼Œä»£è¡¨ä½œæœ‰ã€Šæœ›åºå±±ç€‘å¸ƒã€‹ã€Šè¡Œè·¯éš¾ã€‹ã€Šèœ€é“éš¾ã€‹ã€Šå°†è¿›é…’ã€‹ã€Šæ—©å‘ç™½å¸åŸã€‹ç­‰ã€‚ æç™½æ‰€ä½œè¯èµ‹ï¼Œå°±å…¶å¼€åˆ›æ„ä¹‰åŠè‰ºæœ¯æˆå°±è€Œè¨€ï¼Œäº«æœ‰æä¸ºå´‡é«˜çš„åœ°ä½ï¼Œåä¸–èª‰ä¸ºâ€œè¯—ä»™â€ï¼Œä¸è¯—åœ£æœç”«å¹¶ç§°â€œææœâ€ã€‚

search:
  path: search.json
  enable: true
  field: post
  content: true
